//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DressUp_Scl_Data.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DressUpWebDbEntities : DbContext
    {
        public DressUpWebDbEntities()
            : base("name=DressUpWebDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionPermissons> ActionPermissons { get; set; }
        public virtual DbSet<Ads> Ads { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<GoodsAtlas> GoodsAtlas { get; set; }
        public virtual DbSet<GoodsTypes> GoodsTypes { get; set; }
        public virtual DbSet<Menus> Menus { get; set; }
        public virtual DbSet<OperationRecords> OperationRecords { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<PurchaseList> PurchaseList { get; set; }
        public virtual DbSet<ReceivingInfos> ReceivingInfos { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<ShipmentList> ShipmentList { get; set; }
        public virtual DbSet<ShoppingCarts> ShoppingCarts { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
